### ISSUE TITLE
unzip 0.1.3 install archive is 245mb

### ISSUE THREAD

**Issue by JacekLach** [EvanOxfeld/node-unzip#11]
And due to that takes forever to install.
The offending file is `package/examples/eclipse-jee-juno-SR1-macosx-cocoa-x86_64.tar.gz.zip` in the archive (https://registry.npmjs.org/unzip/-/unzip-0.1.3.tgz).

**Comment by EvanOxfeld** [comment]
The examples directory shouldn't have been published. I'll get a new version out shortly.

**Comment by EvanOxfeld** [comment]
Thanks for reporting this issue. unzip 0.1.3 has been republished to NPM without the large files.
