### ISSUE TITLE
extracted files corrupted

### ISSUE THREAD

**Issue by missinglink** [EvanOxfeld/node-unzip#118]
hi,

we are using `node-unzip` and have recently found a reproducible case where one of the files extracted from the archive is corrupted, both the file size and the shasums of the decompressed file are different when compared to the same archive extracted on the command line. 

the archive is sourced from the US Census Bureau and is valid (as far as I can tell using `unzip -t`)

I've written up the issue in more detail here:
https://github.com/pelias/interpolation/issues/162

**Comment by ZJONSSON** [comment]
@missinglink was this closed because the problem was related to something else, or is this still an issue?
