### ISSUE TITLE
Can't pipe http.incomingMessage to unzip.Parse()

### ISSUE THREAD

**Issue by collin** [EvanOxfeld/node-unzip#39]
This has an error

``` js
module.exports = function zipHandler(request, response, next) {
  request.pipe(unzip.Parse());
}
```

error is:

``` sh
Error: invalid signature: 0x8074b50
    at node_modules/unzip/lib/parse.js:63:13
    at process._tickCallback (node.js:415:13)
```

This works, the file is written to http.zip and I can unzip in in my terminal.

``` js
module.exports = function zipHandler(request, response, next) {
  request.pipe(require('fs').createWriteStream("./http.zip"));
}
```

Looks like the data coming over the wire is correct but piping the request to unzip.Parse() doesn't work, what should I be doing?

**Comment by collin** [comment]
No clue, but after banging the the machine with a wrench long enough and rewriting the thing a few times... It works.

**Comment by totty90** [comment]
Did you found the problem? You are the only result: https://www.google.pt/search?num=100&safe=off&q=%22Error%3A+invalid+signature%3A+0x8074b50%22&oq=%22Error%3A+invalid+signature%3A+0x8074b50%22&gs_l=serp.3...1139.1139.0.1296.1.1.0.0.0.0.98.98.1.1.0....0...1c.1.41.serp..1.0.0.H9avHa47STA

**Comment by collin** [comment]
@totty90 since then we have abandoned efforts to use this library.

Abandon all hope ye who enter...

**Comment by totty90** [comment]
Ok, Now I'm using "archiver" if somebody need to know.
