### ISSUE TITLE
Hangs on archives created with OS X Finder

### ISSUE THREAD

**Issue by ralphholzmann** [EvanOxfeld/node-unzip#8]
When I create an archive using OS X's Finder, and then try to process the archive using unzip, it hangs on the first "entry" event. Here's an example zip file that hangs.

https://dl.dropbox.com/u/47777/Archive.zip

as a point of reference, I've been able to get this error when slowly streaming a zip file to the parser:

```
/node_modules/unzip/node_modules/readable-stream/transform.js:183
    readcb(null, chunk);
    ^
RangeError: Maximum call stack size exceeded
```

**Comment by ralphholzmann** [comment]
Can you point me to any docs on the zip spec? I can give this a shot myself and file a pull request.

**Comment by EvanOxfeld** [comment]
A pull request would be great - I haven't had a chance to investigate. Check out section 4.3 of the pkware spec - http://www.pkware.com/documents/casestudies/APPNOTE.TXT or alternatively the Wikipedia entry - http://en.wikipedia.org/wiki/Zip_(file_format)

**Comment by EvanOxfeld** [comment]
Confirmed that this is related to #10. Closed as a duplicate. A fix is forthcoming.
